#ifndef _KD_CAMERA_HW_H_
#define _KD_CAMERA_HW_H_

#include <mach/mt_gpio.h>

#ifdef MTK_MT6306_SUPPORT
#include <mach/dcl_sim_gpio.h>
#endif

#include <mach/mt_pm_ldo.h>
#include <cust_i2c.h>
#include "pmic_drv.h"

//Analog
#define CAMERA_POWER_VCAM_A         PMIC_APP_MAIN_CAMERA_POWER_A //MT6328_POWER_LDO_VCAMA - LDO_VCAMA_VOLTAGE  2800
//Digital
#define CAMERA_POWER_VCAM_D         PMIC_APP_MAIN_CAMERA_POWER_D //MT6328_POWER_LDO_VCAMD - LDO_VCAMD_VOLTAGE  1500
//AF
#define CAMERA_POWER_VCAM_AF        PMIC_APP_MAIN_CAMERA_POWER_AF //MT6328_POWER_LDO_VCAM_AF - LDO_VCAMAF_VOLTAGE 2800
//digital io
#define CAMERA_POWER_VCAM_IO        PMIC_APP_MAIN_CAMERA_POWER_IO //MT6328_POWER_LDO_VCAM_IO - LDO_VCAMIO_VOLTAGE 1800
//Digital for Sub
#define SUB_CAMERA_POWER_VCAM_D     PMIC_APP_SUB_CAMERA_POWER_D //MT6328_POWER_LDO_VCAMD - LDO_VCAMD_VOLTAGE  1500


//FIXME, should defined in DCT tool
//Main sensor
#define CAMERA_CMRST_PIN            GPIO_CAMERA_CMRST_PIN
#define CAMERA_CMRST_PIN_M_GPIO     GPIO_CAMERA_CMRST_PIN_M_GPIO

#define CAMERA_CMPDN_PIN            GPIO_CAMERA_CMPDN_PIN
#define CAMERA_CMPDN_PIN_M_GPIO     GPIO_CAMERA_CMPDN_PIN_M_GPIO

//FRONT sensor
#define CAMERA_CMRST1_PIN           GPIO_CAMERA_CMRST1_PIN
#define CAMERA_CMRST1_PIN_M_GPIO    GPIO_CAMERA_CMRST1_PIN_M_GPIO

#define CAMERA_CMPDN1_PIN           GPIO_CAMERA_CMPDN1_PIN
#define CAMERA_CMPDN1_PIN_M_GPIO    GPIO_CAMERA_CMPDN1_PIN_M_GPIO

// Define I2C Bus Num
#define SUPPORT_I2C_BUS_NUM1        I2C_CAMERA_MAIN_CHANNEL //0
#define SUPPORT_I2C_BUS_NUM2        I2C_CAMERA_SUB_CHANNEL //0

#endif
